markdown: rdiscount
pygments: true

# site global
url: http://luchanghong.com
title: 向猿猴进阶，python/php程序员的博客。
subtitle: 因何而生？因何而战？程序员的道路走着……
author: luchanghong


# site path
tags_path: /tags.html
category_path: /category.html

# post config
date_format: "%Y-%m-%d"
paginate: 8
pagination_dir: blog/
