markdown: rdiscount
pygments: true

# site global
title: 向猿猴进阶，python/php程序员的博客。
subtitle: 生活因编程而充实，时光因开发而快乐，做一个有追求的程序员！
author: luchanghong


# site path
tags_path: /tags.html

# post config
date_format: "%Y-%m-%d"
paginate: 3
pagination_dir: blog/
