# Site settings
title: "程序员Lunixy的生活和工作"
footer_title: "Lunixy's work and life"
sub_title: "I am an enginner, and work in ChaoYang,Beijing."
description: "Focus on web develop, and the main program languages are PHP and Python."
baseurl: ""

# about author
anthor: lunixy
twitter_username: luchanghong
github_username: luchanghong
email: "luchanghong1990@gmail.com"

# Build settings
# permalink: pretty
paginate: 12

# markdown render and settings
highlighter: pygments
markdown: redcarpet
redcarpet:
    extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]

# collections
collections:
  tech:
    output: true
  life:
    output: true
